config/routes.rb
Examples::Application.routes.draw do

  resources :expenses
  resources :expenses
  resources :scores
  resources :applications
  resources :items
  resources :sponsors
  resources :students
  devise_for :users
  

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/new' => 'devise/registrations#new'
  end

  resources :users
  Wice.define_routes(self, 'queries')

  root :to => "students#index"

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :student
  belongs_to :sponsor
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :student
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :student
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base

   def full_name
   "#{last_name} #{slast_name} #{names}"
   end

   mount_uploader :foto, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
# encoding: utf-8
class HomeController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /students
  def index
    @students_grid = initialize_grid(Student, order: 'id')
  end

  # GET /students/1
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student, notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /students/1
  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /students/1
  def destroy
    @student.destroy
    redirect_to students_url, notice: 'Student was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_params
      params.require(:student).permit(:st_number, :typest, :last_name, :slast_name, :names, :birthdate, :gender, :address, :map_link, :phone, :father_name, :father_work, :mother_name, :mother_work, :sibling, :colonia, :city, :zip_code, :foto, :shoe_size, :tshirt_size, :email, :profession, :notes)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/appliances_helper.rb
module AppliancesHelper
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
  @@code = {}

  def show_code
    n = 0
    content_tag(:ul,
                code_chunks.map do |filename_for_view, code|
                  n += 1

                  content_tag(:li,
                              content_tag(:div,
                                          link_to(filename_for_view, "#collapse#{n}", 'data-toggle' => 'collapse', 'data-parent' => '#code-accordion', :class => 'accordion-toggle'),
                                          class: 'accordion-heading'
                              ) +
                              content_tag(:div,
                                          content_tag(:div, code, class: 'accordion-inner'),
                                          class: 'accordion-body collapse',
                                          style: 'height: 0px;',
                                          id: "collapse#{n}"
                              ),
                              class: 'list-group-item'
                  )
                end.join.html_safe,
                id: 'code-accordion',
                class: 'list-group'
    )
  end

  def code_chunks
    [].tap do |res|
      res << code_for(@controller_file, @controller_file_to_show, :ruby)

      @view_files_dir.each do|filename_for_view, filename|
        filetype = filename_for_view =~ /\.erb/ ? :rhtml : :haml
        res << code_for(filename, filename_for_view, filetype)
      end
    end
  end

  def code_for(filename, filename_for_view, filetype = :ruby)
    code = File.read(filename)
    @@code[filetype] = CodeRay.scan("\n#{code}", filetype).div unless @@code[filename]
    [filename_for_view, @@code[filetype].html_safe]
  end

  def each_example
    @example_map.each do |section|
      section[1].each do |controller, name|
        yield controller, name
      end
    end
  end

  def current_page_title
    each_example do |controller, name|
      if controller.to_s == controller_name
        return name
      end
    end
  end

  def previous_next_example_urls
    previous_example_controller = nil
    next_example_controller     = nil

    _previous_example_controller = nil
    found = false
    each_example do |controller, _name|
      if found
        return previous_example_controller, controller
      end

      if controller.to_s == controller_name
        previous_example_controller = _previous_example_controller
        found = true
      end
      _previous_example_controller = controller
    end
    [previous_example_controller, nil]
  end


end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/situations_helper.rb
module SituationsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :foto %><br>
    <%= image_tag(@student.foto.thumb.url) %><br>
    <%= link_to "Ver", image_path(@student.foto), :target => "_blank" %><br>
  </div>
  <div class="field">
    <%= f.label :st_number %><br>
    <%= f.number_field :st_number %>
  </div>
  <div class="field">
    <%= f.label :typest %><br>
    <%= f.select(:typest, options_for_select([['Estudiante','Estudiante'],['Foraneos','Foraneos'],['Comedor','Comedor'],['Desayunador','Desayunador'],['SSA','SSA']]),{}, {:class => "form-control"} ) %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :slast_name %><br>
    <%= f.text_field :slast_name %>
  </div>
  <div class="field">
    <%= f.label :names %><br>
    <%= f.text_field :names %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.date_select :birthdate, {:start_year => 1980}    %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select(:gender, options_for_select([['Femenino','F'],['Masculino','M']], @student.gender),{}, {:class => "form-control"} ) %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :map_link %><br>
    <%= f.text_field :map_link %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :father_name %><br>
    <%= f.text_field :father_name %>
  </div>
  <div class="field">
    <%= f.label :father_work %><br>
    <%= f.text_field :father_work %>
  </div>
  <div class="field">
    <%= f.label :mother_name %><br>
    <%= f.text_field :mother_name %>
  </div>
  <div class="field">
    <%= f.label :mother_work %><br>
    <%= f.text_field :mother_work %>
  </div>
  <div class="field">
    <%= f.label :sibling %><br>
    <%= f.number_field :sibling %>
  </div>
  <div class="field">
    <%= f.label :colonia %><br>
    <%= f.text_field :colonia %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :shoe_size %><br>
    <%= f.text_field :shoe_size %>
  </div>
  <div class="field">
    <%= f.label :tshirt_size %><br>
    <%=  f.select(:tshirt_size, options_for_select([['EX Small','XS'],['Small','S'],['Medium','M'],['Large','L'],['X-Large','XL']], @student.tshirt_size),{}, {:class => "form-control"} ) %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :profession %><br>
    <%= f.text_field :profession %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/_form_new.html.haml
= form_for(@student) do |f|
  - if @student.errors.any?
    #error_explanation
      %h2
        = pluralize(@student.errors.count, "error")
        prohibited this student from being saved:
      %ul
        - @student.errors.full_messages.each do |message|
          %li= message
  %form.form-inline{:role => "form"}
    .col-sm-2
      = f.label :st_number
      = f.text_field :st_number
    .col-sm-5
      = f.label :typest
      = f.select(:typest, options_for_select([['Estudiante','Estudiante'],['Foraneos','Foraneos'],['Comedor','Comedor'],['Desayunador','Desayunador'],['SSA','SSA']]),{}, {:class => "form-control"} )
    .col-sm-2
      = f.label :last_name
      = f.text_field :last_name
    .col-sm-2
      = f.label :slast_name
      = f.text_field :slast_name
    .col-sm-2
      = f.label :names
      = f.text_field :names
    .col-sm-2
      = f.label :birthdate
      = f.date_select :birthdate, {:start_year => 1980}      
    .col-sm-5
      = f.label :gender
      = f.select(:gender, options_for_select([['Femenino','F'],['Masculino','M']]),{}, {:class => "form-control"} )
    .col-sm-2
      = f.label :father_name
      = f.text_field :father_name
    .col-sm-2
      = f.label :father_work
      = f.text_field :father_work
    .col-sm-2
      = f.label :mother_name
      = f.text_field :mother_name
    .col-sm-2
      = f.label :mother_work
      = f.text_field :mother_work
    .col-sm-2
      = f.label :sibling
      = f.text_field :sibling
    .col-sm-2
      = f.label :address
      = f.text_area :address, {class: "form-control", rows: "2"}
    .col-sm-2
      = f.label :colonia
      = f.text_field :colonia
    .col-sm-2
      = f.label :city
      = f.text_field :city
    .col-sm-2
      = f.label :map_link
      = f.text_field :map_link
    .col-sm-2
      = f.label :phone
      = f.text_field :phone
    .col-sm-2
      = f.file_field :foto
      = image_tag(@student.foto.thumb.url)
    .col-sm-2
      = f.label :shoe_size
      = f.text_field :shoe_size
    .col-sm-2
      = f.label :tshirt_size
      = f.select(:tshirt_size, options_for_select([['EX Small','XS'],['Small','S'],['Medium','M'],['Large','L'],['X-Large','XL']]),{}, {:class => "form-control"} )
    .col-sm-2
      = f.label :email
      = f.text_field :email
    .col-sm-2
      = f.label :profession
      = f.text_field :profession
    .col-sm-2
      = f.label :notes
      = f.text_area :notes, {class: "form-control", rows: "2"}

      .actions
        = f.submit

app/views/students/_grid.html.erb
<%= grid(@students_grid) do |g|

  g.column name:  'Matricula', attribute: 'st_number'
  
  g.column name:  'Paterno', attribute: 'last_name'
  
  g.column  name:  'Materno', attribute: 'slast_name'
     
  g.column  name:  'Nombre(s)', attribute: 'names'

  @now = Date.today

  g.column name: 'Edad', attribute: 'birthdate', filter_type: :rails_time_helper  do |student|
    @age = ((@now - student.birthdate)/365).to_i
  end

  g.column  name:  'Typest', attribute: 'typest'

  g.column   do |student|
    link_to('Edit', edit_student_path(student))
  end

  g.column   do |student|
    link_to('Delete',  student,  method: :delete, data: { confirm: 'Are you sure?' })
  end
end -%>

<%= link_to 'Nuevo Estudiante', new_student_path-%>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.haml
.well.well-sm
  %h2 STUDENTS

= render   'grid'

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form_new' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>St number:</strong>
  <%= @student.st_number %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Slast name:</strong>
  <%= @student.slast_name %>
</p>

<p>
  <strong>Names:</strong>
  <%= @student.names %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @student.birthdate %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @student.gender %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <strong>Map link:</strong>
  <%= @student.map_link %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @student.father_name %>
</p>

<p>
  <strong>Father work:</strong>
  <%= @student.father_work %>
</p>

<p>
  <strong>Mother name:</strong>
  <%= @student.mother_name %>
</p>

<p>
  <strong>Mother work:</strong>
  <%= @student.mother_work %>
</p>

<p>
  <strong>Sibling:</strong>
  <%= @student.sibling %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @student.colonia %>
</p>

<p>
  <strong>City:</strong>
  <%= @student.city %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @student.zip_code %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @student.foto %>
</p>

<p>
  <strong>Shoe size:</strong>
  <%= @student.shoe_size %>
</p>

<p>
  <strong>Tshirt size:</strong>
  <%= @student.tshirt_size %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @student.profession %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @student.notes %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>