config/routes.rb
Examples::Application.routes.draw do

  resources :expenses
  resources :expenses
  resources :scores
  resources :applications
  resources :items
  resources :sponsors
  resources :students
  devise_for :users
  

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/new' => 'devise/registrations#new'
  end

  resources :users
  Wice.define_routes(self, 'queries')

  root :to => "students#index"

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :student
  belongs_to :sponsor
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :student
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :student
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base

   def full_name
   "#{last_name} #{slast_name} #{names}"
   end

   mount_uploader :foto, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :init_example_map
  before_filter :init_current_example_map


  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "login"
    else
      "application"
    end
  end

  def init_current_example_map
    @controller_file_to_show = 'app/controllers/' + controller_name + '_controller.rb'
    @controller_file = File.join(Rails.root, @controller_file_to_show)

    @view_files_dir = {}
    view_files_dir = File.join(Rails.root, 'app/views/' + controller_name)
    Dir.glob("#{view_files_dir}/*").each do |fullpath|
      fullpath =~ /^.+(app\/views\/.+)$/
      @view_files_dir[Regexp.last_match(1)] = fullpath
    end
  end

  def init_example_map
    @example_map = [
      ['REPORTES',
       [
         [:tickets, 'Reportes'],
         [:activities, 'Atenciones'],


       ]
      ],

      ['CATALOGOS',
       [
         [:customers, 'Clientes'],
         [:appliances, 'Dispositivos'],
         [:employees, 'Empleados'],
         [:situations, 'Estatus'],
         [:categories, 'Categorias'],
         [:priorities, 'Prioridades'],
       ]
      ]
    ]
  end


end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /applications
  def index
   #  @applications_grid = initialize_grid(Application, order: 'id')

     @applications_grid = initialize_grid(Application,
                                          order: 'students.last_name',
                                          name: 'grid',
                                          enable_export_to_csv: true,
                                          csv_field_separator: ';',
                                          csv_file_name: 'Applications'
     )


     export_grid_if_requested('grid' => 'grid')

  end
  # GET /applications/1
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  def create
    @application = Application.new(application_params)

    if @application.save
      redirect_to @application, notice: 'Application was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /applications/1
  def update
    if @application.update(application_params)
      redirect_to @application, notice: 'Application was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /applications/1
  def destroy
    @application.destroy
    redirect_to applications_url, notice: 'Application was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def application_params
      params.require(:application).permit(:date, :typesc, :school_name, :school_year, :grade, :level, :score, :other_scholarship, :from, :amount, :approved, :notes, :student_id, :sponsor_id)
    end
end

app/controllers/home_controller.rb
# encoding: utf-8
class HomeController < ApplicationController
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/appliances_helper.rb
module AppliancesHelper
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
  @@code = {}

  def show_code
    n = 0
    content_tag(:ul,
                code_chunks.map do |filename_for_view, code|
                  n += 1

                  content_tag(:li,
                              content_tag(:div,
                                          link_to(filename_for_view, "#collapse#{n}", 'data-toggle' => 'collapse', 'data-parent' => '#code-accordion', :class => 'accordion-toggle'),
                                          class: 'accordion-heading'
                              ) +
                              content_tag(:div,
                                          content_tag(:div, code, class: 'accordion-inner'),
                                          class: 'accordion-body collapse',
                                          style: 'height: 0px;',
                                          id: "collapse#{n}"
                              ),
                              class: 'list-group-item'
                  )
                end.join.html_safe,
                id: 'code-accordion',
                class: 'list-group'
    )
  end

  def code_chunks
    [].tap do |res|
      res << code_for(@controller_file, @controller_file_to_show, :ruby)

      @view_files_dir.each do|filename_for_view, filename|
        filetype = filename_for_view =~ /\.erb/ ? :rhtml : :haml
        res << code_for(filename, filename_for_view, filetype)
      end
    end
  end

  def code_for(filename, filename_for_view, filetype = :ruby)
    code = File.read(filename)
    @@code[filetype] = CodeRay.scan("\n#{code}", filetype).div unless @@code[filename]
    [filename_for_view, @@code[filetype].html_safe]
  end

  def each_example
    @example_map.each do |section|
      section[1].each do |controller, name|
        yield controller, name
      end
    end
  end

  def current_page_title
    each_example do |controller, name|
      if controller.to_s == controller_name
        return name
      end
    end
  end

  def previous_next_example_urls
    previous_example_controller = nil
    next_example_controller     = nil

    _previous_example_controller = nil
    found = false
    each_example do |controller, _name|
      if found
        return previous_example_controller, controller
      end

      if controller.to_s == controller_name
        previous_example_controller = _previous_example_controller
        found = true
      end
      _previous_example_controller = controller
    end
    [previous_example_controller, nil]
  end


end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/situations_helper.rb
module SituationsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.select(:student_id, options_from_collection_for_select(Student.all, :id, :full_name, @application.student_id),{}, {:class => "form-control"} ) %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :school_name %><br>
    <%= f.text_field :school_name %>
  </div>
  <div class="field">
    <%= f.label :school_year %><br>
    <%= f.text_field :school_year %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.text_field :grade %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.select(:level, options_for_select([['Primaria','Primaria'],['Secundaria','Secundaria'],['Preparatoria','Preparatoria']]),{}, {:class => "form-control"} ) %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="field">
    <%= f.label :other_scholarship %><br>
    <%= f.check_box :other_scholarship %>
  </div>
  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :approved %><br>
    <%= f.check_box :approved %>
  </div>
  <div class="field">
    <%= f.label :typesc %><br>
    <%= f.select(:typesc, options_for_select([['Media','Media'],['Completa','Completa']]),{}, {:class => "form-control"} ) %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :sponsor_id %><br>
    <%= f.select(:sponsor_id, options_from_collection_for_select(Sponsor.all, :id, :name, @application.student_id),{}, {:class => "form-control"} ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/_grid.html.erb
<%= grid(@applications_grid) do |g|

  @now = Date.today

  g.column name: 'Edad', attribute: 'birthdate', filter_type: :rails_time_helper ,  assoc: :student do |application|
   @age = ((@now - application.student.birthdate)/365).to_i
    end

  g.column  name:  'Sexo', attribute: 'gender',  assoc: :student

  g.column  name:  'Paterno', attribute: 'last_name',  assoc: :student
  
  g.column  name:  'Materno', attribute: 'slast_name',  assoc: :student
   
  g.column  name:  'Nombres', attribute: 'names',  assoc: :student

  g.column name:  'Date', attribute: 'date'
  
  g.column name:  'School', attribute: 'school_name'
  
  g.column  name:  'School Year', attribute: 'school_year'
     
  g.column  name:  'Grade', attribute: 'grade'
  
  g.column  name:  'Level', attribute: 'level'
  
  g.column  name:  'Score', attribute: 'score'
  
  g.column  name:  'Grade', attribute: 'grade'
  
  g.column name:  'Other Scholarship', attribute: 'other_scholarship'
  
  g.column  name:  'From', attribute: 'from'
  
  g.column  name:  'Amount', attribute: 'amount'
  
  g.column  name:  'Approved', attribute: 'approved'

  g.column  name:  'Typesc', attribute: 'typesc'

  g.column  name:  'Shoe Size', attribute: 'shoe_size',  assoc: :student
  
  g.column  name:  'Notes', attribute: 'notes'
  
  
  
  
  g.column   do |application|
    link_to('Edit', edit_application_path(application))
  end
end -%>

<%= link_to 'New Application', new_application_path-%>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.haml
.well.well-sm
  %h2 APPLICATIONS
%p

= render  'grid'

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @application.date %>
</p>

<p>
  <strong>School name:</strong>
  <%= @application.school_name %>
</p>

<p>
  <strong>School year:</strong>
  <%= @application.school_year %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @application.grade %>
</p>

<p>
  <strong>Score:</strong>
  <%= @application.score %>
</p>

<p>
  <strong>Other scholarship:</strong>
  <%= @application.other_scholarship %>
</p>

<p>
  <strong>From:</strong>
  <%= @application.from %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @application.amount %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @application.approved %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @application.notes %>
</p>

<p>
  <strong>Student:</strong>
  <%= @application.student %>
</p>

<p>
  <strong>Sponsor:</strong>
  <%= @application.sponsor %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>