config/routes.rb
Examples::Application.routes.draw do

  resources :expenses
  resources :expenses
  resources :scores
  resources :applications
  resources :items
  resources :sponsors
  resources :students
  devise_for :users
  

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/new' => 'devise/registrations#new'
  end

  resources :users
  Wice.define_routes(self, 'queries')

  root :to => "students#index"

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :student
  belongs_to :sponsor
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :student
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :student
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base

   def full_name
   "#{last_name} #{slast_name} #{names}"
   end

   mount_uploader :foto, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
# encoding: utf-8
class HomeController < ApplicationController
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /scores
  def index
    @scores_grid = initialize_grid(Score, order: 'id')
  end

  # GET /scores/1
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  def create
    @score = Score.new(score_params)

    if @score.save
      redirect_to @score, notice: 'Score was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /scores/1
  def update
    if @score.update(score_params)
      redirect_to @score, notice: 'Score was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /scores/1
  def destroy
    @score.destroy
    redirect_to scores_url, notice: 'Score was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def score_params
      params.require(:score).permit(:month, :year, :score, :student_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/appliances_helper.rb
module AppliancesHelper
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
  @@code = {}

  def show_code
    n = 0
    content_tag(:ul,
                code_chunks.map do |filename_for_view, code|
                  n += 1

                  content_tag(:li,
                              content_tag(:div,
                                          link_to(filename_for_view, "#collapse#{n}", 'data-toggle' => 'collapse', 'data-parent' => '#code-accordion', :class => 'accordion-toggle'),
                                          class: 'accordion-heading'
                              ) +
                              content_tag(:div,
                                          content_tag(:div, code, class: 'accordion-inner'),
                                          class: 'accordion-body collapse',
                                          style: 'height: 0px;',
                                          id: "collapse#{n}"
                              ),
                              class: 'list-group-item'
                  )
                end.join.html_safe,
                id: 'code-accordion',
                class: 'list-group'
    )
  end

  def code_chunks
    [].tap do |res|
      res << code_for(@controller_file, @controller_file_to_show, :ruby)

      @view_files_dir.each do|filename_for_view, filename|
        filetype = filename_for_view =~ /\.erb/ ? :rhtml : :haml
        res << code_for(filename, filename_for_view, filetype)
      end
    end
  end

  def code_for(filename, filename_for_view, filetype = :ruby)
    code = File.read(filename)
    @@code[filetype] = CodeRay.scan("\n#{code}", filetype).div unless @@code[filename]
    [filename_for_view, @@code[filetype].html_safe]
  end

  def each_example
    @example_map.each do |section|
      section[1].each do |controller, name|
        yield controller, name
      end
    end
  end

  def current_page_title
    each_example do |controller, name|
      if controller.to_s == controller_name
        return name
      end
    end
  end

  def previous_next_example_urls
    previous_example_controller = nil
    next_example_controller     = nil

    _previous_example_controller = nil
    found = false
    each_example do |controller, _name|
      if found
        return previous_example_controller, controller
      end

      if controller.to_s == controller_name
        previous_example_controller = _previous_example_controller
        found = true
      end
      _previous_example_controller = controller
    end
    [previous_example_controller, nil]
  end


end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/situations_helper.rb
module SituationsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.select(:student_id, options_from_collection_for_select(Student.all, :id, :full_name, @score.student_id),{}, {:class => "form-control"} ) %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/_grid.html.erb
<%= grid(@scores_grid) do |g|
   
  g.column  name:  'Paterno', attribute: 'last_name', assoc: :student
   
  g.column  name:  'Usuario', attribute: 'slast_name', assoc: :student
  
  g.column  name:  'Usuario', attribute: 'names', assoc: :student
  
  g.column name:  'Month', attribute: 'month'
  
  g.column name:  'Year', attribute: 'year'
  
  g.column name:  'Score', attribute: 'score'
  
  g.column   do |score|
    link_to('Edit', edit_score_path(score))
  end

  g.column   do |score|
    link_to('Delete',  score,  method: :delete, data: { confirm: 'Are you sure?' })
  end
end -%>

<%= link_to 'New Score', new_score_path-%>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.haml
.well.well-sm
  %h2 SCORES

= render   'grid'

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Month:</strong>
  <%= @score.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @score.year %>
</p>

<p>
  <strong>Score:</strong>
  <%= @score.score %>
</p>

<p>
  <strong>Student:</strong>
  <%= @score.student %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>