config/routes.rb
Examples::Application.routes.draw do

  resources :expenses
  resources :expenses
  resources :scores
  resources :applications
  resources :items
  resources :sponsors
  resources :students
  devise_for :users
  

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/new' => 'devise/registrations#new'
  end

  resources :users
  Wice.define_routes(self, 'queries')

  root :to => "students#index"

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :student
  belongs_to :sponsor
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :student
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :student
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base

   def full_name
   "#{last_name} #{slast_name} #{names}"
   end

   mount_uploader :foto, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/appliances_helper.rb
module AppliancesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/situations_helper.rb
module SituationsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/expenses2/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.text_field :item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses2/_grid.html.erb
<%= grid(@expenses_grid) do |g|
	
  g.column  name:  'Paterno', attribute: 'last_name',  assoc: :student
  
  g.column  name:  'Materno', attribute: 'slast_name',  assoc: :student
   
  g.column  name:  'Nombres', attribute: 'names',  assoc: :student	
   
  g.column  name:  'Name', attribute: 'month'
  
  g.column name:  'Description', attribute: 'year'
  
  g.column name:  'Amount', attribute: 'amount'
  
  g.column   do |expense|
    link_to('Edit', edit_expense_path(expense))
  end
end -%>

<%= link_to 'New Expense', new_expense_path-%>

app/views/expenses2/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses2/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Month</th>
      <th>Year</th>
      <th>Amount</th>
      <th>Student</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.month %></td>
        <td><%= expense.year %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.student %></td>
        <td><%= expense.item %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses2/index.html.haml
.well.well-sm
  %h2 EXPENSES

= render   'grid'

app/views/expenses2/new.html.erb
<h1>New Expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses2/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Month:</strong>
  <%= @expense.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @expense.year %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Student:</strong>
  <%= @expense.student %>
</p>

<p>
  <strong>Item:</strong>
  <%= @expense.item %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title FANLAP 
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-default.navbar-default{:role => "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => students_path('index')} FANLAP
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              =link_to 'New Student', new_student_path
            %li
              =link_to 'Students', students_path('index')
            %li
              =link_to 'New Application', new_application_path
            %li
              =link_to 'Applications', applications_path('index')
            %li
              =link_to 'Scores', scores_path('index')
            %li
              =link_to 'Expenses', expenses_path('index')
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Catalogs
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li
                  %a=link_to 'Sponsor', sponsors_path('index')
                %li
                  %a=link_to 'Items', items_path('index')
          .container-fluid
            .row
              = image_tag("header.jpg", alt: "Header", :height => "50", :width => "500", :class => "img-rounded")
              %ul.nav.navbar-nav.navbar-right
                %li
                  %a{:href => "#"}
                    %span.glyphicon.glyphicon-user
                    = current_user.email
                %li
                  %a{:href => destroy_user_session_path}
                    %span.glyphicon.glyphicon-log-in
                    Cerrar Sesion

    .container-fluid

      =yield



      %hr

      %footer

app/views/layouts/login.html.haml
!!! 5
%html
  %head
    %title
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .well-sm
      %center
        %img.img-circle= image_tag("logo.png", alt: "Example Image", :height => "136", :width => "204")

    .container-fluid

      %header

        =yield


      %hr

      %footer